version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: koya_trpo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - './sql/:/docker-entrypoint-initdb.d/'
      - './postgres-data:/var/lib/postgresql/data'
